# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img_url',
            field=models.URLField(default='/static/images/a2.jpg'),
        ),
    ]
