# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170727_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
