# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_count',
            field=models.IntegerField(null=True),
        ),
    ]
