# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170729_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to='%Y/%m'),
        ),
    ]
